version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  ipFile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: ../../log/ipCrawler.log
  neoIpCrawler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: ../../log/neoIpCrawler.log
  neo:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: ../../log/neo.log
  zhihuFile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: ../../log/zhihuCrawler.log
    encoding : UTF-8
  rootFile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: ../../log/rootFileIpCrawler.log
loggers:
#  py2neo.cypher:
#    level: INFO
#    handlers: [neo]
  app.crawlerIP:
    level: DEBUG
    handlers: [console,ipFile]
    propagate: no
  app.zhihu:
    level: INFO
    handlers: [console,zhihuFile]
  __main__:
    level: INFO
    handlers: [console,zhihuFile]
#root:
#  level: DEBUG
#  handlers: [console,rootFile]